---
# handlers file for grub
- name: update grub
  command: "{{ grub_update_grub_command }}"
  when:
    - ansible_connection != "docker"
  notify:
    - reboot

- name: reboot
  when:
    - grub_restart_after_update == True
  reboot:
